### ISSUE TITLE
0xC00007B Windows 10 x86_64

### ISSUE THREAD

**Issue by PibePlayer** [PibePlayer/MultiMC5-Cracked#6]
[Issue](https://github.com/AfoninZ/MultiMC5-Cracked/pull/23#issuecomment-835573849)

**Comment by PibePlayer** [comment]
On the Install - fixup_bundle:
```
-- 18/64: copying 'C:/hostedtoolcache/windows/Python/3.7.9/x64/VCRUNTIME140.dll'
-- 19/64: copying 'C:/Program Files/Microsoft SDKs/Azure/Azure Dev Spaces CLI/api-ms-win-crt-convert-l1-1-0.dll'
-- 20/64: copying 'C:/Program Files/Microsoft SDKs/Azure/Azure Dev Spaces CLI/api-ms-win-crt-heap-l1-1-0.dll'
-- 21/64: copying 'C:/Program Files/Microsoft SDKs/Azure/Azure Dev Spaces CLI/api-ms-win-crt-runtime-l1-1-0.dll'
-- 22/64: copying 'C:/Program Files/Microsoft SDKs/Azure/Azure Dev Spaces CLI/api-ms-win-crt-stdio-l1-1-0.dll'
-- 23/64: copying 'C:/Program Files/Microsoft SDKs/Azure/Azure Dev Spaces CLI/api-ms-win-crt-string-l1-1-0.dll'
-- 24/64: copying 'D:/MultiMC-Cracked/libMultiMC_iconfix.dll'
-- warning: resolved_item == resolved_embedded_item - not copying...
-- 25/64: copying 'D:/MultiMC-Cracked/libMultiMC_logic.dll'
-- warning: resolved_item == resolved_embedded_item - not copying...
-- 26/64: copying 'D:/MultiMC-Cracked/libMultiMC_nbt++.dll'
-- warning: resolved_item == resolved_embedded_item - not copying...
-- 27/64: copying 'D:/MultiMC-Cracked/libMultiMC_quazip.dll'
-- warning: resolved_item == resolved_embedded_item - not copying...
-- 28/64: copying 'C:/Strawberry/c/bin/libssp-0.dll'
-- 29/64: copying 'C:/Program Files/Microsoft Service Fabric/bin/Fabric/Fabric.Code/zlib1.dll'
```
As you can see, it copies a lot of x64 dlls, fixing it now

**Comment by Neptune650** [comment]
Oh yeah!, you must remove "C:/Program Files/Microsoft SDKs/Azure/Azure Dev Spaces CLI", "C:/Program Files/Microsoft Service Fabric/bin/Fabric/Fabric.Code" and "C:/hostedtoolcache/windows/Python/3.7.9/x64" (maybe also "C:/Strawberry/c/bin") from the path.

**Comment by Xpl0itU** [comment]
fixed by taking the official multimc release and dragging it into the cracked version, replacing all, then take the multimc exe and libMultiMC_gui.dll from the cracked version and put it into that folder, replace all. Hacky workaround but it worked for me

**Comment by Neptune650** [comment]
Yep, is due to that broken path problem.

**Comment by Neptune650** [comment]
I fixed it!, check: https://github.com/Sebastian-byte/MultiMC5-Cracked/commit/60a6b55265cd654699acdb5b17889f46d567b361

**Comment by Neptune650** [comment]
I recommend using my method, is better and doesn't conflicts with the linker.

**Comment by PibePlayer** [comment]
@Sebastian-byte can you make a pull request?

**Comment by Neptune650** [comment]
I can't fork this repository, you must add these lines manually.

**Comment by PibePlayer** [comment]
@Sebastian-byte I cherry picked the commits and uploaded them here, now it should work as expected

**Comment by Neptune650** [comment]
Yep, it works, you can close this issue now.
